apiVersion: v2
name: kubevirt-flatcar
description: Helm chart for Flatcar-based Cluster API templates on KubeVirt
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/jseguillon/kubevirt-capi-easy
